name: Handle Triggered Release

on:
  repository_dispatch:
    types:
      - release-triggered

permissions:
  contents: write

jobs:
  build-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{github.event.client_payload.version}}
        name: ${{github.event.client_payload.version}} Starters
        draft: false
        prerelease: false
