name: Handle Triggered Release

on:
  repository_dispatch:
    types:
      - release-triggered

jobs:
  handle-release:
    runs-on: ubuntu-latest

    steps:
      - env:
          VERSION: ${{ github.event.client_payload.version }}
        run: echo $VERSION
      - name: Print hello
        run: echo "HELLO"
